

<!DOCTYPE HTML>
<HTML LANG="AR">
<HEAD>
<TITLE>KADYSOFT</TITLE>
<META CHARSET="UTF-8">
<META NAME="VIEWPORT" CONTENT="WIDTH=DEVICE-WIDTH, INITIAL-SCALE=1.0">
<STYLE>TD {
HEIGHT:5PX;
MAX-WIDTH:100%;
WHITE-SPACE:NOWRAP;
}
TABLE {
HEIGHT:5PX;
MAX-WIDTH:100%;
HEIGHT:100%;
WHITE-SPACE:NOWRAP;
}
TR {
HEIGHT:5PX;
MAX-WIDTH:100%;
WHITE-SPACE:NOWRAP;
}/* CENTERED WATERMARK */
    .WATERMARK {
      POSITION: FIXED;
      TOP: 50%;
      LEFT: 50%;
      TRANSFORM: TRANSLATE(-50%, -50%) ROTATE(-45DEG);
      BACKGROUND-IMAGE: URL('LOGO.PNG'); /* REPLACE WITH THE PATH TO T & C GARMENTS LOGO */
      BACKGROUND-REPEAT: NO-REPEAT;
      BACKGROUND-SIZE: CONTAIN;
      WIDTH: 300PX;
      HEIGHT: 200PX;
      OPACITY: 0.3;
      POINTER-EVENTS: NONE;
      Z-INDEX: 1000;
    }
    /* REPEATED WATERMARK */
    .WATERMARK-REPEATED {
      POSITION: FIXED;
      TOP: 0;
      LEFT: 0;
      WIDTH: 100%;
      HEIGHT: 100%;
      BACKGROUND-IMAGE: URL('LOGO.PNG'); /* REPLACE WITH THE PATH TO T & C GARMENTS LOGO */
      BACKGROUND-REPEAT: REPEAT;
      BACKGROUND-SIZE: 300PX 200PX;
      OPACITY: 0.2;
      POINTER-EVENTS: NONE;
      Z-INDEX: 1000;
    }</STYLE></HEAD>
<BODY><CENTER>
<DIV CLASS="WATERMARK"></DIV>


<!-- CREATING RECIPE FROM KADYSOFT LTD.-->


<!DOCTYPE HTML>
<HTML CONTENTEDITABLE LANG="AR">
 <HEAD> 
  <TITLE>KADYSOFT</TITLE> 
  <META CHARSET="UTF-8"> 
  <META NAME="VIEWPORT" CONTENT="WIDTH=DEVICE-WIDTH, INITIAL-SCALE=1.0"> 
  <STYLE>TD {
HEIGHT:5PX;
MAX-WIDTH:100%;
WHITE-SPACE:NOWRAP;
}
TABLE {
HEIGHT:5PX;
MAX-WIDTH:100%;
HEIGHT:100%;
WHITE-SPACE:NOWRAP;
}
TR {
HEIGHT:5PX;
MAX-WIDTH:100%;
WHITE-SPACE:NOWRAP;
}/* CENTERED WATERMARK */
    .WATERMARK {
      POSITION: FIXED;
      TOP: 50%;
      LEFT: 50%;
      TRANSFORM: TRANSLATE(-50%, -50%) ROTATE(-45DEG);
      BACKGROUND-IMAGE: URL('LOGO.PNG'); /* REPLACE WITH THE PATH TO T & C GARMENTS LOGO */
      BACKGROUND-REPEAT: NO-REPEAT;
      BACKGROUND-SIZE: CONTAIN;
      WIDTH: 300PX;
      HEIGHT: 200PX;
      OPACITY: 0.3;
      POINTER-EVENTS: NONE;
      Z-INDEX: 1000;
    }
    /* REPEATED WATERMARK */
    .WATERMARK-REPEATED {
      POSITION: FIXED;
      TOP: 0;
      LEFT: 0;
      WIDTH: 100%;
      HEIGHT: 100%;
      BACKGROUND-IMAGE: URL('LOGO.PNG'); /* REPLACE WITH THE PATH TO T & C GARMENTS LOGO */
      BACKGROUND-REPEAT: REPEAT;
      BACKGROUND-SIZE: 300PX 200PX;
      OPACITY: 0.2;
      POINTER-EVENTS: NONE;
      Z-INDEX: 1000;
    }</STYLE> 
 </HEAD> 
 <BODY> 
  <CENTER> 
   <CENTER> 
    <DIV CLASS="WATERMARK"></DIV> 
    <!-- CREATING RECIPE FROM KADYSOFT LTD.--> 
   </CENTER> 
  </CENTER> 
  <META CHARSET="UTF-8"> 
  <META NAME="VIEWPORT" CONTENT="WIDTH=DEVICE-WIDTH, INITIAL-SCALE=1.0"> 
  <STYLE>TD {
HEIGHT:5PX;
MAX-WIDTH:100%;
WHITE-SPACE:NOWRAP;
}
TABLE {
HEIGHT:5PX;
MAX-WIDTH:100%;
HEIGHT:100%;
WHITE-SPACE:NOWRAP;
}
TR {
HEIGHT:5PX;
MAX-WIDTH:100%;
WHITE-SPACE:NOWRAP;
}/* CENTERED WATERMARK */
    .WATERMARK {
      POSITION: FIXED;
      TOP: 50%;
      LEFT: 50%;
      TRANSFORM: TRANSLATE(-50%, -50%) ROTATE(-45DEG);
      BACKGROUND-IMAGE: URL('LOGO.PNG'); /* REPLACE WITH THE PATH TO T & C GARMENTS LOGO */
      BACKGROUND-REPEAT: NO-REPEAT;
      BACKGROUND-SIZE: CONTAIN;
      WIDTH: 300PX;
      HEIGHT: 200PX;
      OPACITY: 0.3;
      POINTER-EVENTS: NONE;
      Z-INDEX: 1000;
    }
    /* REPEATED WATERMARK */
    .WATERMARK-REPEATED {
      POSITION: FIXED;
      TOP: 0;
      LEFT: 0;
      WIDTH: 100%;
      HEIGHT: 100%;
      BACKGROUND-IMAGE: URL('LOGO.PNG'); /* REPLACE WITH THE PATH TO T & C GARMENTS LOGO */
      BACKGROUND-REPEAT: REPEAT;
      BACKGROUND-SIZE: 300PX 200PX;
      OPACITY: 0.2;
      POINTER-EVENTS: NONE;
      Z-INDEX: 1000;
    }</STYLE> 
  <CENTER> 
   <CENTER> 
    <CENTER> 
     <CENTER> 
      <DIV CLASS="WATERMARK"></DIV> 
      <!-- CREATING RECIPE FROM KADYSOFT LTD.--> 
     </CENTER> 
    </CENTER> 
   </CENTER> 
  </CENTER> 
  <META CHARSET="UTF-8"> 
  <META NAME="VIEWPORT" CONTENT="WIDTH=DEVICE-WIDTH, INITIAL-SCALE=1.0"> 
  <STYLE>TD {
HEIGHT:5PX;
MAX-WIDTH:100%;
WHITE-SPACE:NOWRAP;
}
TABLE {
HEIGHT:5PX;
MAX-WIDTH:100%;
HEIGHT:100%;
WHITE-SPACE:NOWRAP;
}
TR {
HEIGHT:5PX;
MAX-WIDTH:100%;
WHITE-SPACE:NOWRAP;
}/* CENTERED WATERMARK */
    .WATERMARK {
      POSITION: FIXED;
      TOP: 50%;
      LEFT: 50%;
      TRANSFORM: TRANSLATE(-50%, -50%) ROTATE(-45DEG);
      BACKGROUND-IMAGE: URL('LOGO.PNG'); /* REPLACE WITH THE PATH TO T & C GARMENTS LOGO */
      BACKGROUND-REPEAT: NO-REPEAT;
      BACKGROUND-SIZE: CONTAIN;
      WIDTH: 300PX;
      HEIGHT: 200PX;
      OPACITY: 0.3;
      POINTER-EVENTS: NONE;
      Z-INDEX: 1000;
    }
    /* REPEATED WATERMARK */
    .WATERMARK-REPEATED {
      POSITION: FIXED;
      TOP: 0;
      LEFT: 0;
      WIDTH: 100%;
      HEIGHT: 100%;
      BACKGROUND-IMAGE: URL('LOGO.PNG'); /* REPLACE WITH THE PATH TO T & C GARMENTS LOGO */
      BACKGROUND-REPEAT: REPEAT;
      BACKGROUND-SIZE: 300PX 200PX;
      OPACITY: 0.2;
      POINTER-EVENTS: NONE;
      Z-INDEX: 1000;
    }</STYLE> 
  <CENTER> 
   <CENTER> 
    <CENTER> 
     <CENTER> 
      <CENTER> 
       <CENTER> 
        <DIV CLASS="WATERMARK"></DIV> 
        <!-- CREATING RECIPE FROM KADYSOFT LTD.--> 
       </CENTER> 
      </CENTER> 
     </CENTER> 
    </CENTER> 
   </CENTER> 
  </CENTER> 
  <STYLE>
        BODY {
             NONE;
             NONE;
             NONE;
             NONE;
        }
    </STYLE> 
  <CENTER> 
   <CENTER> 
    <CENTER> 
     <CENTER> 
      <CENTER> 
       <CENTER> 
        <SCRIPT>
        ('DRAGSTART', FUNCTION(EVENT) {
            
        });

        ('DROP', FUNCTION(EVENT) {
            
        });

        ('CONTEXTMENU', FUNCTION(EVENT) {
            
        });
    </SCRIPT> 
        <SCRIPT>
  
  WINDOW.ADDEVENTLISTENER(`CONTEXTMENU`, (E) => {
    
});
  
  </SCRIPT> 
       </CENTER> 
      </CENTER> 
     </CENTER> 
    </CENTER> 
   </CENTER> 
  </CENTER> 
  <META CHARSET="UTF-8"> 
  <META NAME="VIEWPORT" CONTENT="WIDTH=DEVICE-WIDTH, USER-SCALABLE=NO, INITIAL-SCALE=1.0, MAXIMUM-SCALE=1.0, MINIMUM-SCALE=1.0"> 
  <META HTTP-EQUIV="X-UA-COMPATIBLE" CONTENT="IE=EDGE"> 
  <CENTER> 
   <CENTER> 
    <CENTER> 
     <CENTER> 
      <CENTER> 
       <SCRIPT>
            
            ('KEYDOWN', EVENT => {
  CONSOLE.LOG(`USER PRESSED: ${EVENT.KEY}`);
  
  RETURN FALSE;
});
            
            </SCRIPT> 
       <SCRIPT>
        ('KEYDOWN', FUNCTION (EVENT) {
            // DISABLE SPECIFIC KEYS OR KEY COMBINATIONS
            
        });
    </SCRIPT> 
       <TABLE ID="EXTABLE" STYLE="BORDER-COLLAPSE: COLLAPSE;" BORDER="1"> 
        <TBODY> 
         <TR STYLE="HEIGHT: 24PX;"> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 146.015625PX; HEIGHT: 24PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 196.109375PX; HEIGHT: 24PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 124.921875PX; HEIGHT: 24PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 175.46875PX; HEIGHT: 24PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 107.734375PX; HEIGHT: 24PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 111.734375PX; HEIGHT: 24PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 134.953125PX; HEIGHT: 24PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 202.84375PX; HEIGHT: 24PX;"></TD> 
          <TD STYLE="BORDER: 3PX DOUBLE #000000; PADDING: 10PX; BACKGROUND-COLOR: #FFFFFF; TEXT-ALIGN: CENTER; VERTICAL-ALIGN: MIDDLE; HEIGHT: 144PX; WIDTH: 209.03125PX; BACKGROUND-POSITION: INITIAL INITIAL; BACKGROUND-REPEAT: INITIAL INITIAL;" ROWSPAN="7"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 215.984375PX; HEIGHT: 24PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: YELLOW; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 223.265625PX; HEIGHT: 24PX;"><SPAN STYLE="FONT-SIZE: 14PT;">BLANKET</SPAN></TD> 
         </TR> 
         <TR STYLE="HEIGHT: 20PX;"> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 146.015625PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFF00; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 196.109375PX; HEIGHT: 20PX;">PRODUCTION RECIPE</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFF00; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 124.921875PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFF00; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 175.46875PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFF00; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 107.734375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFF00; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 111.734375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: LEFT; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 134.953125PX; HEIGHT: 20PX;">DATE:</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 202.84375PX; HEIGHT: 20PX;">27/01/2026</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 215.984375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 223.265625PX; HEIGHT: 20PX;"></TD> 
         </TR> 
         <TR STYLE="HEIGHT: 20PX;"> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: LEFT; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 146.015625PX; HEIGHT: 20PX;">CUST :</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 196.109375PX; HEIGHT: 20PX;">LEVIS</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 124.921875PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 175.46875PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 107.734375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 111.734375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: LEFT; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 134.953125PX; HEIGHT: 20PX;">WASH NAME :</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 202.84375PX; HEIGHT: 20PX;">BLACK SPROUT OPT2</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 215.984375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 223.265625PX; HEIGHT: 20PX;"></TD> 
         </TR> 
         <TR STYLE="HEIGHT: 20PX;"> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: LEFT; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 146.015625PX; HEIGHT: 20PX;">PO NO :</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 196.109375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 124.921875PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 175.46875PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 107.734375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 111.734375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: LEFT; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 134.953125PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 202.84375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 215.984375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 223.265625PX; HEIGHT: 20PX;"></TD> 
         </TR> 
         <TR STYLE="HEIGHT: 20PX;"> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: LEFT; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 146.015625PX; HEIGHT: 20PX;">PO AMOUNT :</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 196.109375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 124.921875PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 175.46875PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 107.734375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 111.734375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 134.953125PX; HEIGHT: 20PX;">KG :</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 202.84375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 215.984375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 223.265625PX; HEIGHT: 20PX;"></TD> 
         </TR> 
         <TR STYLE="HEIGHT: 20PX;"> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: LEFT; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 146.015625PX; HEIGHT: 20PX;">FABRIC NAME :</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 196.109375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 124.921875PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 175.46875PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 107.734375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 111.734375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 134.953125PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 202.84375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 215.984375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 223.265625PX; HEIGHT: 20PX;"></TD> 
         </TR> 
         <TR STYLE="HEIGHT: 20PX;"> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: LEFT; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 146.015625PX; HEIGHT: 20PX;">MACHINE NO :</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 196.109375PX; HEIGHT: 20PX;">OPERATOR</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 124.921875PX; HEIGHT: 20PX;">SPINING NO</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 175.46875PX; HEIGHT: 20PX;">OPERATOR</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 107.734375PX; HEIGHT: 20PX;">DRYER NO</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 111.734375PX; HEIGHT: 20PX;">OPERATOR</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 134.953125PX; HEIGHT: 20PX;">PCS :</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 202.84375PX; HEIGHT: 20PX;">6</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 215.984375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 223.265625PX; HEIGHT: 20PX;"></TD> 
         </TR> 
         <TR STYLE="HEIGHT: 21PX;"> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 146.015625PX; HEIGHT: 21PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 196.109375PX; HEIGHT: 21PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 124.921875PX; HEIGHT: 21PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 175.46875PX; HEIGHT: 21PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 107.734375PX; HEIGHT: 21PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 111.734375PX; HEIGHT: 21PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 134.953125PX; HEIGHT: 21PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 203.84375PX; HEIGHT: 21PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 229.03125PX; HEIGHT: 21PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 216.984375PX; HEIGHT: 21PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 223.265625PX; HEIGHT: 21PX;"></TD> 
         </TR> 
         <TR STYLE="HEIGHT: 20PX;"> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFF00; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 146.015625PX; HEIGHT: 20PX;">COMMENTS</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFF00; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 196.109375PX; HEIGHT: 20PX;">ACTION NAME</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFF00; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 124.921875PX; HEIGHT: 20PX;">TIME(MIN)</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFF00; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 175.46875PX; HEIGHT: 20PX;">TEMP</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFF00; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 107.734375PX; HEIGHT: 20PX;">LITER'S</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFF00; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 111.734375PX; HEIGHT: 20PX;">AMT</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFF00; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 134.953125PX; HEIGHT: 20PX;">UNIT'S</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFF00; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 203.84375PX; HEIGHT: 20PX;">CHEMICAL</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFF00; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 229.03125PX; HEIGHT: 20PX;">CHEMICAL NAME</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFF00; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 216.984375PX; HEIGHT: 20PX;">CHEMICAL LOT NUMBER</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFF00; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 223.265625PX; HEIGHT: 20PX;">CHEMICAL DEFINITIONS</TD> 
         </TR> 
         <TR STYLE="HEIGHT: 20PX;"> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 146.015625PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 196.109375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 124.921875PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 175.46875PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 107.734375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 111.734375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 134.953125PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 203.84375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 229.03125PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-SIZE: 12PT; WIDTH: 216.984375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="WIDTH: 223.265625PX; HEIGHT: 20PX;"></TD> 
         </TR> 
         <TR STYLE="HEIGHT: 20PX;"> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 146.015625PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 196.109375PX; HEIGHT: 20PX;">BNG</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 124.921875PX; HEIGHT: 20PX;">10</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 175.46875PX; HEIGHT: 20PX;">50</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 107.734375PX; HEIGHT: 20PX;">50</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 111.734375PX; HEIGHT: 20PX;">300</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 134.953125PX; HEIGHT: 20PX;">GR</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 203.84375PX; HEIGHT: 20PX;">BNG</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 229.03125PX; HEIGHT: 20PX;"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">LAVA CELL BNG</B></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 216.984375PX; HEIGHT: 20PX;"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">MZ10200</B></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 223.265625PX; HEIGHT: 20PX;"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">إنزيم للتنعيم وإزالة الوبرة</B></TD> 
         </TR> 
         <TR> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 146.015625PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 196.109375PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 124.921875PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 175.46875PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 107.734375PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 111.734375PX;">20</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 134.953125PX;">GR</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 203.84375PX;">ACID</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 229.03125PX;"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">ACETIC ACID (CH3COOH)</B></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 216.984375PX;"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">N/A</B></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 223.265625PX;"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">حمض خفيف لتعادل القلوية</B></TD> 
         </TR> 
         <TR STYLE="HEIGHT: 20PX;"> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 146.015625PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 196.109375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 124.921875PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 175.46875PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 107.734375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 111.734375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 134.953125PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 203.84375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 229.03125PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 216.984375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 223.265625PX; HEIGHT: 20PX;"></TD> 
         </TR> 
         <TR STYLE="HEIGHT: 20PX;"> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 146.015625PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 196.109375PX; HEIGHT: 20PX;">RINSE</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 124.921875PX; HEIGHT: 20PX;">2</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 175.46875PX; HEIGHT: 20PX;">20</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 107.734375PX; HEIGHT: 20PX;">60</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 111.734375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 134.953125PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 203.84375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 229.03125PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 216.984375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 223.265625PX; HEIGHT: 20PX;"></TD> 
         </TR> 
         <TR STYLE="HEIGHT: 20PX;"> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 146.015625PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 196.109375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 124.921875PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 175.46875PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 107.734375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 111.734375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 134.953125PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 203.84375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 229.03125PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 216.984375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 223.265625PX; HEIGHT: 20PX;"></TD> 
         </TR> 
         <TR STYLE="HEIGHT: 20PX;"> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 146.015625PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 196.109375PX; HEIGHT: 20PX;">FIX</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 124.921875PX; HEIGHT: 20PX;">5</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 175.46875PX; HEIGHT: 20PX;">40</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 107.734375PX; HEIGHT: 20PX;">50</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 111.734375PX; HEIGHT: 20PX;">300</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 134.953125PX; HEIGHT: 20PX;">GR</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 203.84375PX; HEIGHT: 20PX;">FIX.</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 229.03125PX; HEIGHT: 20PX;"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">ROYAFIX FX</B></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 216.984375PX; HEIGHT: 20PX;"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">TR2024025331</B></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 223.265625PX; HEIGHT: 20PX;"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">مادة تثبيت</B></TD> 
         </TR> 
         <TR STYLE="HEIGHT: 20PX;"> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 146.015625PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 196.109375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 124.921875PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 175.46875PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 107.734375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 111.734375PX; HEIGHT: 20PX;">20</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 134.953125PX; HEIGHT: 20PX;">GR</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 203.84375PX; HEIGHT: 20PX;">ACID</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 229.03125PX; HEIGHT: 20PX;"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">ACETIC ACID (CH3COOH)</B></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 216.984375PX; HEIGHT: 20PX;"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">N/A</B></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 223.265625PX; HEIGHT: 20PX;"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">حمض خفيف لتعادل القلوية</B></TD> 
         </TR> 
         <TR STYLE="HEIGHT: 20PX;"> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 146.015625PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 196.109375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 124.921875PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 175.46875PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 107.734375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 111.734375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 134.953125PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 203.84375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 229.03125PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 216.984375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 223.265625PX; HEIGHT: 20PX;"></TD> 
         </TR> 
         <TR STYLE="HEIGHT: 20PX;"> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 146.015625PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 196.109375PX; HEIGHT: 20PX;">SOFT</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 124.921875PX; HEIGHT: 20PX;">5</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 175.46875PX; HEIGHT: 20PX;">20</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 107.734375PX; HEIGHT: 20PX;">50</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 111.734375PX; HEIGHT: 20PX;">2</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 134.953125PX; HEIGHT: 20PX;">KG</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 203.84375PX; HEIGHT: 20PX;">SOFTN OZN</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 229.03125PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 216.984375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 223.265625PX; HEIGHT: 20PX;"></TD> 
         </TR> 
         <TR STYLE="HEIGHT: 20PX;"> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 146.015625PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 196.109375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 124.921875PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 175.46875PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 107.734375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 111.734375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 134.953125PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 203.84375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 229.03125PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 216.984375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 223.265625PX; HEIGHT: 20PX;"></TD> 
         </TR> 
         <TR STYLE="HEIGHT: 20PX;"> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 146.015625PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 196.109375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 124.921875PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFF00; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 175.46875PX; HEIGHT: 20PX;">رص في العصارة 3 دقائق</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 107.734375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 111.734375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 134.953125PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 203.84375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 229.03125PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 216.984375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 223.265625PX; HEIGHT: 20PX;"></TD> 
         </TR> 
         <TR STYLE="HEIGHT: 20PX;"> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 146.015625PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 196.109375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 124.921875PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFF00; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 175.46875PX; HEIGHT: 20PX;">EXTRACT &AMP; DRYER</TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 107.734375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 111.734375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 134.953125PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 203.84375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 229.03125PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 216.984375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 223.265625PX; HEIGHT: 20PX;"></TD> 
         </TR> 
         <TR STYLE="HEIGHT: 20PX;"> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 146.015625PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 196.109375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 124.921875PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 175.46875PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 107.734375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 111.734375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 134.953125PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 203.84375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 229.03125PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 216.984375PX; HEIGHT: 20PX;"></TD> 
          <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFFFFF; COLOR: #000000; TEXT-ALIGN: CENTER; FONT-WEIGHT: BOLD; FONT-SIZE: 12PT; WIDTH: 223.265625PX; HEIGHT: 20PX;"></TD> 
         </TR> 
        </TBODY> 
       </TABLE> 
      </CENTER> 
     </CENTER> 
    </CENTER> 
   </CENTER> 
  </CENTER> 
  <STYLE>
BODY {
BACKGROUND-IMAGE: URL("LEVIS.BMP");
BACKGROUND-POSITION: CENTER;
HEIGHT: 170PX;
BACKGROUND-POSITION-X:550PX;  BACKGROUND-REPEAT: NO-REPEAT;
BACKGROUND-SIZE: 120PX 90PX;
}
</STYLE> 
  <STYLE>
BODY {
  BACKGROUND-IMAGE: URL("LEVIS.BMP");
  BACKGROUND-POSITION: CENTER;
  HEIGHT: 170PX;
BACKGROUND-POSITION-X:550PX;  BACKGROUND-REPEAT: NO-REPEAT;
  BACKGROUND-SIZE: 120PX 90PX;
}
</STYLE> 
  <STYLE>
BODY {
  BACKGROUND-IMAGE: URL("LEVIS.BMP");
  BACKGROUND-POSITION: CENTER;
  HEIGHT: 170PX;
BACKGROUND-POSITION-X:550PX;  BACKGROUND-REPEAT: NO-REPEAT;
  BACKGROUND-SIZE: 120PX 90PX;
}
</STYLE>  
 </BODY>
</HTML>


</CENTER>
</BODY>
</HTML>
<B ID="SIGNNAME">MR_MUHAMMET SIGNATURE: </B><IMG ID="SIGNIMAGE" SRC="FILE://Z:\MODELS\MR_MUHAMMET.PNG" WIDTH="300" HEIGHT="90" ALT="DEVELOPED BY KADYSOFT LTD (AHMED ELKADY)." STYLE="BORDER-COLOR:BLACK;BORDER-WIDTH:10PX;">


<STYLE>
BODY {
  BACKGROUND-IMAGE: URL("LEVIS.BMP");
  BACKGROUND-POSITION: CENTER;
  HEIGHT: 170PX;
BACKGROUND-POSITION-X:550PX;  BACKGROUND-REPEAT: NO-REPEAT;
  BACKGROUND-SIZE: 120PX 90PX;
}
</STYLE>
