

<!DOCTYPE HTML>
<HTML LANG="AR">
<HEAD>
<TITLE>KADYSOFT</TITLE>
<META CHARSET="UTF-8">
<META NAME="VIEWPORT" CONTENT="WIDTH=DEVICE-WIDTH, INITIAL-SCALE=1.0">
<STYLE>TD {
HEIGHT:5PX;
MAX-WIDTH:100%;
WHITE-SPACE:NOWRAP;
}
TABLE {
HEIGHT:5PX;
MAX-WIDTH:100%;
HEIGHT:100%;
WHITE-SPACE:NOWRAP;
}
TR {
HEIGHT:5PX;
MAX-WIDTH:100%;
WHITE-SPACE:NOWRAP;
}/* CENTERED WATERMARK */
    .WATERMARK {
      POSITION: FIXED;
      TOP: 50%;
      LEFT: 50%;
      TRANSFORM: TRANSLATE(-50%, -50%) ROTATE(-45DEG);
      BACKGROUND-IMAGE: URL('LOGO.PNG'); /* REPLACE WITH THE PATH TO T & C GARMENTS LOGO */
      BACKGROUND-REPEAT: NO-REPEAT;
      BACKGROUND-SIZE: CONTAIN;
      WIDTH: 300PX;
      HEIGHT: 200PX;
      OPACITY: 0.3;
      POINTER-EVENTS: NONE;
      Z-INDEX: 1000;
    }
    /* REPEATED WATERMARK */
    .WATERMARK-REPEATED {
      POSITION: FIXED;
      TOP: 0;
      LEFT: 0;
      WIDTH: 100%;
      HEIGHT: 100%;
      BACKGROUND-IMAGE: URL('LOGO.PNG'); /* REPLACE WITH THE PATH TO T & C GARMENTS LOGO */
      BACKGROUND-REPEAT: REPEAT;
      BACKGROUND-SIZE: 300PX 200PX;
      OPACITY: 0.2;
      POINTER-EVENTS: NONE;
      Z-INDEX: 1000;
    }</STYLE></HEAD>
<BODY><CENTER>
<DIV CLASS="WATERMARK"></DIV>


<!-- CREATING RECIPE FROM KADYSOFT LTD.-->


<HTML CONTENTEDITABLE LANG="AR">
 <HEAD> 
  <TITLE>KADYSOFT</TITLE> 
  <META CHARSET="UTF-8"> 
  <META NAME="VIEWPORT" CONTENT="WIDTH=DEVICE-WIDTH, INITIAL-SCALE=1.0"> 
  <STYLE>TD {
HEIGHT:5PX;
MAX-WIDTH:100%;
WHITE-SPACE:NOWRAP;
}
TABLE {
HEIGHT:5PX;
MAX-WIDTH:100%;
HEIGHT:100%;
WHITE-SPACE:NOWRAP;
}
TR {
HEIGHT:5PX;
MAX-WIDTH:100%;
WHITE-SPACE:NOWRAP;
}</STYLE> 
 </HEAD> 
 <BODY> 
  <CENTER> 
   <!-- CREATING RECIPE FROM KADYSOFT LTD.--> 
   <TABLE ID="EXTABLE" STYLE="WIDTH: 1686PX; HEIGHT: 1068PX;" BORDER="1" CELLSPACING="0"> 
    <TBODY> 
     <TR STYLE="HEIGHT: 24PX;"> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.125PX; HEIGHT: 24PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.078125PX; HEIGHT: 24PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"><B>PRODUCTION RECIPE</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.09375PX; HEIGHT: 24PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.34375PX; HEIGHT: 24PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 81.953125PX; HEIGHT: 24PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 85.953125PX; HEIGHT: 24PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.109375PX; HEIGHT: 24PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"><B>DATE:</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 174.953125PX; HEIGHT: 24PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"><B>31/01/2026</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 267.171875PX; HEIGHT: 24PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 189.859375PX; HEIGHT: 24PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 195.359375PX; TEXT-ALIGN: CENTER; HEIGHT: 24PX;"><SPAN STYLE="FONT-SIZE: 14PT;"><STRONG>BLANKET</STRONG></SPAN></TD> 
     </TR> 
     <TR STYLE="HEIGHT: 18PX;"> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.125PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"><B>CUST :</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.078125PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"><B>COLIN'S</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.09375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.34375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 81.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 85.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.109375PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>WASH NAME :</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 174.953125PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"><STRONG>RINSE WADLEY WASH</STRONG></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 267.171875PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 189.859375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 195.359375PX; HEIGHT: 18PX;"></TD> 
     </TR> 
     <TR STYLE="HEIGHT: 18PX;"> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.125PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"><B>PO NO :</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.078125PX; HEIGHT: 18PX;" ALIGN="CENTER"><STRONG>CL1082959-41</STRONG></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.09375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.34375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 81.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 85.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.109375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 174.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 267.171875PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 189.859375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 195.359375PX; HEIGHT: 18PX;"></TD> 
     </TR> 
     <TR STYLE="HEIGHT: 18PX;"> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.125PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"><B>PO AMOUNT :</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.078125PX; HEIGHT: 18PX;" ALIGN="CENTER"><STRONG>60552509</STRONG></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.09375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.34375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 81.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 85.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.109375PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>KG :</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 174.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>15</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 267.171875PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 189.859375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 195.359375PX; HEIGHT: 18PX;"></TD> 
     </TR> 
     <TR STYLE="HEIGHT: 18PX;"> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.125PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"><B>FABRIC NAME :</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.078125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.09375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.34375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 81.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 85.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.109375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 174.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 267.171875PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 189.859375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 195.359375PX; HEIGHT: 18PX;"></TD> 
     </TR> 
     <TR STYLE="HEIGHT: 18PX;"> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.125PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"><B>MACHINE NO :</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.078125PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>OPERATOR</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.09375PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>SPINING NO</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.34375PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>OPERATOR</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 81.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>DRYER NO </B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 85.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>OPERATOR</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.109375PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>PCS :</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 174.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>BLANKET</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 267.171875PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 189.859375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 195.359375PX; HEIGHT: 18PX;"></TD> 
     </TR> 
     <TR STYLE="HEIGHT: 18PX;"> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.125PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.078125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.09375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.34375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 81.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 85.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.109375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 174.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 267.171875PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 189.859375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 195.359375PX; HEIGHT: 18PX;"></TD> 
     </TR> 
     <TR STYLE="HEIGHT: 18PX;"> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.125PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"><B>ACTION NO</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.078125PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"><B>ACTION NAME</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.09375PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"><B>TIME(MIN)</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.34375PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"><B>TEMP</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 81.953125PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"><B>LITER'S</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 85.953125PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"><B>AMT</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.109375PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"><B>UNIT'S</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 174.953125PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"><B>CHEMICAL</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 267.171875PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"><B>CHEMICAL NAME</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 189.859375PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"><B>CHEMICAL LOT NUMBER</B></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 195.359375PX; HEIGHT: 18PX; BACKGROUND-COLOR: #FFEE00; TEXT-ALIGN: CENTER;"><B>CHEMICAL DEFINITIONS</B></TD> 
     </TR> 
     <TR STYLE="HEIGHT: 18PX;"> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.125PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.078125PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.09375PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.34375PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 81.953125PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 85.953125PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.109375PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 174.953125PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 267.171875PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 189.859375PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 195.359375PX; HEIGHT: 18PX;"></TD> 
     </TR> 
     <TR STYLE="HEIGHT: 18PX;"> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.125PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.078125PX; TEXT-ALIGN: CENTER; HEIGHT: 18PX;"><STRONG>RINSE</STRONG></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.09375PX; TEXT-ALIGN: CENTER; HEIGHT: 18PX;"><STRONG>2</STRONG></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.34375PX; TEXT-ALIGN: CENTER; HEIGHT: 18PX;"><STRONG>20</STRONG></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 81.953125PX; TEXT-ALIGN: CENTER; HEIGHT: 18PX;"><STRONG>150</STRONG></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 85.953125PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.109375PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 174.953125PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 267.171875PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 189.859375PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 195.359375PX; HEIGHT: 18PX;"></TD> 
     </TR> 
     <TR STYLE="HEIGHT: 18PX;"> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.125PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.078125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.09375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.34375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 81.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 85.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.109375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 174.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 267.171875PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 189.859375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 195.359375PX; HEIGHT: 18PX;"></TD> 
     </TR> 
     <TR STYLE="HEIGHT: 18PX;"> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.125PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.078125PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>BNG</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.09375PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>10</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.34375PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>40</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 81.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>120</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 85.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>300</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.109375PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>GR</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 174.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>BNG</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 267.171875PX; HEIGHT: 18PX;" ALIGN="CENTER"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">LAVA CELL BNG</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 189.859375PX; HEIGHT: 18PX;" ALIGN="CENTER"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">MZ10200</B></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 195.359375PX; HEIGHT: 18PX;"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">إنزيم للتنعيم وإزالة الوبرة</B></TD> 
     </TR> 
     <TR STYLE="HEIGHT: 18PX;"> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.125PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.078125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.09375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.34375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 81.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 85.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>120</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.109375PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>GR</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 174.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>ACID</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 267.171875PX; HEIGHT: 18PX;" ALIGN="CENTER"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">ACETIC ACID (CH3COOH)</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 189.859375PX; HEIGHT: 18PX;" ALIGN="CENTER"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">N/A</B></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 195.359375PX; HEIGHT: 18PX;"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">حمض خفيف لتعادل القلوية</B></TD> 
     </TR> 
     <TR STYLE="HEIGHT: 18PX;"> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.125PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.078125PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.09375PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.34375PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 81.953125PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 85.953125PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.109375PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 174.953125PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 267.171875PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 189.859375PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 195.359375PX; HEIGHT: 18PX;"></TD> 
     </TR> 
     <TR STYLE="HEIGHT: 18PX;"> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.125PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.078125PX; TEXT-ALIGN: CENTER; HEIGHT: 18PX;"><STRONG>RINSE</STRONG></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.09375PX; TEXT-ALIGN: CENTER; HEIGHT: 18PX;"><STRONG>2</STRONG></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.34375PX; TEXT-ALIGN: CENTER; HEIGHT: 18PX;"><STRONG>20</STRONG></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 81.953125PX; TEXT-ALIGN: CENTER; HEIGHT: 18PX;"><STRONG>150</STRONG></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 85.953125PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.109375PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 174.953125PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 267.171875PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 189.859375PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 195.359375PX; HEIGHT: 18PX;"></TD> 
     </TR> 
     <TR STYLE="HEIGHT: 18PX;"> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.125PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.078125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.09375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.34375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 81.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 85.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.109375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 174.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 267.171875PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 189.859375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 195.359375PX; HEIGHT: 18PX;"></TD> 
     </TR> 
     <TR STYLE="HEIGHT: 18PX;"> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.125PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.078125PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>BLEACH (1)</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.09375PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>5</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.34375PX; HEIGHT: 18PX;" ALIGN="CENTER"><STRONG>20</STRONG></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 81.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"><STRONG>120</STRONG></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 85.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"><STRONG>1</STRONG></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.109375PX; HEIGHT: 18PX;" ALIGN="CENTER"><STRONG>KG</STRONG></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 174.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"><STRONG>HYPO</STRONG></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 267.171875PX; HEIGHT: 18PX;" ALIGN="CENTER"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">SODIUM HYPOCHLORIDE (NAOCL)</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 189.859375PX; HEIGHT: 18PX;" ALIGN="CENTER"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">N/A</B></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 195.359375PX; HEIGHT: 18PX;"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">مبيض ومعقم قوي</B></TD> 
     </TR> 
     <TR STYLE="HEIGHT: 18PX;"> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.125PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.078125PX; HEIGHT: 18PX;"><B></B></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.09375PX; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"><B>5</B></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.34375PX; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"><STRONG></STRONG></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 81.953125PX; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"><STRONG></STRONG></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 85.953125PX; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"><STRONG>1</STRONG></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.109375PX; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"><STRONG>KG</STRONG></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 174.953125PX; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"><STRONG>HYPO</STRONG></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 267.171875PX; HEIGHT: 18PX;"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">SODIUM HYPOCHLORIDE (NAOCL)</B></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 189.859375PX; HEIGHT: 18PX;"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">N/A</B></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 195.359375PX; HEIGHT: 18PX;"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">مبيض ومعقم قوي</B></TD> 
     </TR> 
     <TR STYLE="HEIGHT: 18PX;"> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.125PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.078125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.09375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.34375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 81.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 85.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.109375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 174.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 267.171875PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 189.859375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 195.359375PX; HEIGHT: 18PX;"></TD> 
     </TR> 
     <TR STYLE="HEIGHT: 18PX;"> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.125PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.078125PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>RINSE </B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.09375PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>2</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.34375PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>20</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 81.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>150</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 85.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.109375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 174.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 267.171875PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 189.859375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 195.359375PX; HEIGHT: 18PX;"></TD> 
     </TR> 
     <TR STYLE="HEIGHT: 18PX;"> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.125PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.078125PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.09375PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.34375PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 81.953125PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 85.953125PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.109375PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 174.953125PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 267.171875PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 189.859375PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 195.359375PX; HEIGHT: 18PX;"></TD> 
     </TR> 
     <TR STYLE="HEIGHT: 18PX;"> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.125PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.078125PX; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"><STRONG>BLEACH (2)</STRONG></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.09375PX; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"><STRONG>5</STRONG></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.34375PX; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"><STRONG>20</STRONG></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 81.953125PX; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"><STRONG>120</STRONG></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 85.953125PX; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"><STRONG>1</STRONG></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.109375PX; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"><STRONG>KG</STRONG></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 174.953125PX; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"><STRONG>HYPO</STRONG></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 267.171875PX; HEIGHT: 18PX;"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">SODIUM HYPOCHLORIDE (NAOCL)</B></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 189.859375PX; HEIGHT: 18PX;"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">N/A</B></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 195.359375PX; HEIGHT: 18PX;"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">مبيض ومعقم قوي</B></TD> 
     </TR> 
     <TR STYLE="HEIGHT: 18PX;"> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.125PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.078125PX; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.09375PX; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"><STRONG>5</STRONG></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.34375PX; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 81.953125PX; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 85.953125PX; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"><STRONG>1</STRONG></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.109375PX; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"><STRONG>KG</STRONG></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 174.953125PX; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"><STRONG>HYPO</STRONG></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 267.171875PX; HEIGHT: 18PX;"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">SODIUM HYPOCHLORIDE (NAOCL)</B></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 189.859375PX; HEIGHT: 18PX;"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">N/A</B></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 195.359375PX; HEIGHT: 18PX;"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">مبيض ومعقم قوي</B></TD> 
     </TR> 
     <TR STYLE="HEIGHT: 18PX;"> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.125PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.078125PX; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.09375PX; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.34375PX; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 81.953125PX; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 85.953125PX; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.109375PX; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 174.953125PX; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 267.171875PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 189.859375PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 195.359375PX; HEIGHT: 18PX;"></TD> 
     </TR> 
     <TR STYLE="HEIGHT: 18PX;"> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.125PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.078125PX; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"><STRONG>RINSE</STRONG></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.09375PX; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"><STRONG>2</STRONG></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.34375PX; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"><STRONG>20</STRONG></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 81.953125PX; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"><STRONG>120</STRONG></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 85.953125PX; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.109375PX; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 174.953125PX; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 267.171875PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 189.859375PX; HEIGHT: 18PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 195.359375PX; HEIGHT: 18PX;"></TD> 
     </TR> 
     <TR STYLE="HEIGHT: 18PX;"> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.125PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.078125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.09375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.34375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 81.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 85.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.109375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 174.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 267.171875PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 189.859375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 195.359375PX; HEIGHT: 18PX;"></TD> 
     </TR> 
     <TR STYLE="HEIGHT: 18PX;"> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.125PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.078125PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>SULFITE</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.09375PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>8</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.34375PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>20</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 81.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>120</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 85.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>300</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.109375PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>GR</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 174.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>SULFITE</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 267.171875PX; HEIGHT: 18PX;" ALIGN="CENTER"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">SODIUM METABISULFITE (NA2S2O5)</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 189.859375PX; HEIGHT: 18PX;" ALIGN="CENTER"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">N/A</B></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 195.359375PX; HEIGHT: 18PX;"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">مادة مختزلة ومزيل للكلور</B></TD> 
     </TR> 
     <TR STYLE="HEIGHT: 18PX;"> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.125PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.078125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.09375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.34375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 81.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 85.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.109375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 174.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 267.171875PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 189.859375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 195.359375PX; HEIGHT: 18PX;"></TD> 
     </TR> 
     <TR STYLE="HEIGHT: 18PX;"> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.125PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.078125PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>RINSE </B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.09375PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>2</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.34375PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>20</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 81.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>150</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 85.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.109375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 174.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 267.171875PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 189.859375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 195.359375PX; HEIGHT: 18PX;"></TD> 
     </TR> 
     <TR STYLE="HEIGHT: 18PX;"> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.125PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.078125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.09375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.34375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 81.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 85.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.109375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 174.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 267.171875PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 189.859375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 195.359375PX; HEIGHT: 18PX;"></TD> 
     </TR> 
     <TR STYLE="HEIGHT: 18PX;"> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.125PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.078125PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>SOFT</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.09375PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>4</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.34375PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>20</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 81.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>120</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 85.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>1</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.109375PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>KG</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 174.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>SOFT ANTI OZON</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 267.171875PX; HEIGHT: 18PX;" ALIGN="CENTER"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">ROSOFT NYI</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 189.859375PX; HEIGHT: 18PX;" ALIGN="CENTER"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">TR2024127147</B></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 195.359375PX; HEIGHT: 18PX;"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">مادة منعم للأقمشة</B></TD> 
     </TR> 
     <TR STYLE="HEIGHT: 18PX;"> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.125PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.078125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.09375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.34375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 81.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 85.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>120</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.109375PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>GR</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 174.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>ACID</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 267.171875PX; HEIGHT: 18PX;" ALIGN="CENTER"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">ACETIC ACID (CH3COOH)</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 189.859375PX; HEIGHT: 18PX;" ALIGN="CENTER"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">N/A</B></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 195.359375PX; HEIGHT: 18PX;"><B STYLE="DISPLAY:BLOCK; TEXT-ALIGN:CENTER;">حمض خفيف لتعادل القلوية</B></TD> 
     </TR> 
     <TR STYLE="HEIGHT: 18PX;"> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.125PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.078125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.09375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.34375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 81.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 85.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.109375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 174.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 267.171875PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 189.859375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 195.359375PX; HEIGHT: 18PX;"></TD> 
     </TR> 
     <TR STYLE="HEIGHT: 18PX;"> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.125PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.078125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.09375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="SELECTAREA" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.34375PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"><B>EXTRACT &AMP; DRYER</B></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 81.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 85.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.109375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 174.953125PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 267.171875PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 189.859375PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 195.359375PX; HEIGHT: 18PX;"></TD> 
     </TR> 
     <TR> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.125PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.078125PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.09375PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.34375PX;"><B></B></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 81.953125PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 85.953125PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.109375PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 174.953125PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 267.171875PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 189.859375PX;"></TD> 
      <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 195.359375PX;"></TD> 
     </TR> 
     <TR> 
      <TD STYLE="WIDTH: 11.1111%;"></TD> 
      <TD STYLE="WIDTH: 11.1111%;"></TD> 
      <TD STYLE="WIDTH: 11.1111%;"></TD> 
      <TD STYLE="WIDTH: 11.1111%;"></TD> 
      <TD STYLE="WIDTH: 11.1111%;"></TD> 
      <TD STYLE="WIDTH: 11.1111%;"></TD> 
      <TD STYLE="WIDTH: 11.1111%;"></TD> 
      <TD STYLE="WIDTH: 11.1111%;"></TD> 
      <TD STYLE="WIDTH: 11.1111%; BACKGROUND-COLOR: #F6FF00; BORDER-COLOR: #FF0000; TEXT-ALIGN: CENTER;"><B>RECIPE TIME :</B> <U><B>113.3</B></U> <B>MINS.</B></TD> 
      <TD STYLE="WIDTH: 11.1111%; BACKGROUND-COLOR: #F6FF00; BORDER-COLOR: #FF0000; TEXT-ALIGN: CENTER;"><U><B>1.9</B></U> <B>HOURS.</B></TD> 
      <TD STYLE="WIDTH: 11.1111%;"></TD> 
     </TR> 
    </TBODY> 
   </TABLE> 
  </CENTER> 
  <STYLE>
BODY {
  BACKGROUND-IMAGE: URL("NULL.BMP");
  BACKGROUND-POSITION: CENTER;
  HEIGHT: 170PX;
BACKGROUND-POSITION-X:550PX;  BACKGROUND-REPEAT: NO-REPEAT;
  BACKGROUND-SIZE: 120PX 90PX;
}
</STYLE>  
 </BODY>
</HTML>


</CENTER>
</BODY>
</HTML>
<B ID="SIGNNAME">MR_MUHAMMET SIGNATURE: </B><IMG ID="SIGNIMAGE" SRC="FILE://Z:\MODELS\MR_MUHAMMET.PNG" WIDTH="300" HEIGHT="90" ALT="DEVELOPED BY KADYSOFT LTD (AHMED ELKADY)." STYLE="BORDER-COLOR:BLACK;BORDER-WIDTH:10PX;">


<STYLE>
BODY {
  BACKGROUND-IMAGE: URL("COLINS.BMP");
  BACKGROUND-POSITION: CENTER;
  HEIGHT: 170PX;
BACKGROUND-POSITION-X:550PX;  BACKGROUND-REPEAT: NO-REPEAT;
  BACKGROUND-SIZE: 120PX 90PX;
}
</STYLE>
